# Generated by Django 2.1.5 on 2019-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
