# Generated by Django 2.1.5 on 2019-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20190120_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
